default_deploy_mode = "upload"

[upload]
auth_token = "YOUR TOKEN HERE"
branch = "default"

hostname = "screeps.com"
ssl = true
port = 443

# for full syntax, see
# https://github.com/daboross/screeps-in-rust-via-wasm/blob/master/screeps-defaults.toml
